fixtures:
  repositories:
    libpam_ssh: "git://github.com/coxley/puppet-libpam-ssh"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    apt: "git://github.com/puppetlabs/puppetlabs-apt"
