notifications:
  email:
    - codey@yelp.com

rvm:
  - 1.9.3
  - 2.0.0

script: "bundle exec rake spec"

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.6.0"
